### ISSUE TITLE
REWARD FILE IS MISSING

### ISSUE THREAD

**Issue by rahulrauni** [YidingYu/DLMA#1]
Hello sir,
Myself Rahul Raj Final year student from Nit Hamirpur, Himachal Pradesh, India. I saw your paper related to Deep-Reinforcement Learning Multiple Access for Heterogeneous Wireless Networks , it is really good work. i am also exporing this topic and want to run the file /DLMA/codes/RNN/agent+EB-ALOHA and it shows some error that OSError: rewards/reward1_len50000_q0.2_M4_E1000_F20_B64_gamma0.9_alpha1_idx1.txt not found.

please provide that file also and if possible please upload this file on github. i remain thankful to you.

**Comment by rahulrauni** [comment]
is there any update?

**Comment by basith3c3r9** [comment]
I have also observed the same problem. 
@rahulrauni @YidingYu

Can you please check if you have any updates? 


Error:
------------------------------------------
---------- Start processing ... ----------
------------------------------------------
100% 50000/50000 [46:05<00:00, 18.08it/s]
Traceback (most recent call last):
  File "run_DQN.py", line 92, in <module>
    main(env.window_size, M, E, F, B, gamma, alpha, idx, max_iter)
  File "run_DQN.py", line 49, in main
    with open(f'rewards/reward1_len{max_iter}_W{W}_M{M}_E{E}_F{F}_B{B}_gamma{gamma}_alpha{alpha}_idx{idx}.txt', 'w') as my_agent:
FileNotFoundError: [Errno 2] No such file or directory: 'rewards/reward1_len50000_W4_M20_E1000_F20_B64_gamma0.9_alpha0_idx1.txt'

**Comment by siyv6** [comment]
I have also observed the same problem.
@rahulrauni @YidingYu @basith3c3r9 
Can you please check if you have any updates?

**Comment by basith3c3r9** [comment]
The problem has been resolved. What you need to do is to manually create a folder in the same directory and rename it to "rewards".
You can do this using the command mkdir rewards or right click on the DLMA folder and click new folder then rename it to rewards

**Comment by lmnsqeez** [comment]
had the same issue ...
creating the rewards folder solved it!!!
